[server]
# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 1000

[theme]
# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
base = "light"